### ISSUE TITLE
Weird issue when joining the game

### ISSUE THREAD

**Issue by part1cleth1ef** [Podrum/PodrumLegacy#123]
### Summary

Game refuses to allow my account to join the server

### Reproduction Steps

install the server, setup a virtualenv with python 3.8, pip install -r requirements.txt and launch __main__.py

### Expected Results

the game would let me in?

### Actual Results

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
Exception in thread Thread-6:
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-3:
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 90, in load_worker
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self.load_chunk(item[0], item[1])
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 51, in load_chunk
    self._target(*self._args, **self._kwargs)
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 90, in load_worker
    self._target(*self._args, **self._kwargs)
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 90, in load_worker
    chunk: object = self.provider.get_chunk(x, z)
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/anvil.py", line 105, in get_chunk
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 90, in load_worker
    self.load_chunk(item[0], item[1])
    self.run()
    chunk_data: bytes = reg.get_chunk_data(chunk_index[0], chunk_index[1])
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/region.py", line 52, in get_chunk_data
    self.load_chunk(item[0], item[1])
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 51, in load_chunk
    self.load_chunk(item[0], item[1])
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 51, in load_chunk
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 51, in load_chunk
  File "/usr/lib/python3.9/threading.py", line 892, in run
    chunk: object = self.provider.get_chunk(x, z)
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/anvil.py", line 105, in get_chunk
    chunk: object = self.provider.get_chunk(x, z)
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/anvil.py", line 105, in get_chunk
    offset: int = binary_converter.read_unsigned_triad_be(file.read(3))
  File "/home/primus/dev/podium/Podrum/venv/lib/python3.9/site-packages/binary_utils/binary_converter.py", line 101, in read_unsigned_triad_be
    self._target(*self._args, **self._kwargs)
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 90, in load_worker
    chunk_data: bytes = reg.get_chunk_data(chunk_index[0], chunk_index[1])
    return struct.unpack(">I", b"\x00" + data)[0]
    chunk: object = self.provider.get_chunk(x, z)
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/anvil.py", line 105, in get_chunk
struct.error: unpack requires a buffer of 4 bytes
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 90, in load_worker
    self.load_chunk(item[0], item[1])
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 51, in load_chunk
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/region.py", line 52, in get_chunk_data
    self.load_chunk(item[0], item[1])
    chunk: object = self.provider.get_chunk(x, z)
    chunk_data: bytes = reg.get_chunk_data(chunk_index[0], chunk_index[1])
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/region.py", line 52, in get_chunk_data
    chunk_data: bytes = reg.get_chunk_data(chunk_index[0], chunk_index[1])
  File "/home/primus/dev/podium/Podrum/podrum/world/world.py", line 51, in load_chunk
    offset: int = binary_converter.read_unsigned_triad_be(file.read(3))
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/anvil.py", line 104, in get_chunk
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/region.py", line 52, in get_chunk_data
  File "/home/primus/dev/podium/Podrum/venv/lib/python3.9/site-packages/binary_utils/binary_converter.py", line 101, in read_unsigned_triad_be
    reg: object = region(region_path)
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/region.py", line 40, in __init__
    chunk: object = self.provider.get_chunk(x, z)
    offset: int = binary_converter.read_unsigned_triad_be(file.read(3))
  File "/home/primus/dev/podium/Podrum/venv/lib/python3.9/site-packages/binary_utils/binary_converter.py", line 101, in read_unsigned_triad_be
    return struct.unpack(">I", b"\x00" + data)[0]
struct.error: unpack requires a buffer of 4 bytes
    offset: int = binary_converter.read_unsigned_triad_be(file.read(3))
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/anvil.py", line 105, in get_chunk
  File "/home/primus/dev/podium/Podrum/venv/lib/python3.9/site-packages/binary_utils/binary_converter.py", line 101, in read_unsigned_triad_be
    os.remove(path + ".lock")
    return struct.unpack(">I", b"\x00" + data)[0]
struct.error: unpack requires a buffer of 4 bytes
    chunk_data: bytes = reg.get_chunk_data(chunk_index[0], chunk_index[1])
FileNotFoundError: [Errno 2] No such file or directory: '/home/primus/dev/podium/Podrum/worlds/world/region/r.0.0.mca.lock'
    return struct.unpack(">I", b"\x00" + data)[0]
struct.error: unpack requires a buffer of 4 bytes
  File "/home/primus/dev/podium/Podrum/podrum/world/provider/anvil/region.py", line 52, in get_chunk_data
    offset: int = binary_converter.read_unsigned_triad_be(file.read(3))
  File "/home/primus/dev/podium/Podrum/venv/lib/python3.9/site-packages/binary_utils/binary_converter.py", line 101, in read_unsigned_triad_be
    return struct.unpack(">I", b"\x00" + data)[0]
struct.error: unpack requires a buffer of 4 bytes
```

### System Information

[INFO: 18:52] This server is running Podrum version 0.0.6 Platinum on API 0.0.1. This version is licensed under the GPL v2.0 license.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by HunterAzar** [comment]
Same error for me

**Comment by HunterAzar** [comment]
@part1cleth1ef fixed
