### ISSUE TITLE
MCRegion based world format bug

### ISSUE THREAD

**Issue by SpiceX** [Podrum/PodrumLegacy#126]
### Summary

This server software is not joinable

### Reproduction Steps

Start the server and join

### Expected Results

Join to the server

### Actual Results

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/diego/Documentos/Podrum/podrum/world/world.py", line 90, in load_worker
    self.load_chunk(item[0], item[1])
  File "/home/diego/Documentos/Podrum/podrum/world/world.py", line 51, in load_chunk
    chunk: object = self.provider.get_chunk(x, z)
  File "/home/diego/Documentos/Podrum/podrum/world/provider/anvil/anvil.py", line 105, in get_chunk
    chunk_data: bytes = reg.get_chunk_data(chunk_index[0], chunk_index[1])
  File "/home/diego/Documentos/Podrum/podrum/world/provider/anvil/region.py", line 52, in get_chunk_data
    offset: int = binary_converter.read_unsigned_triad_be(file.read(3))
  File "/home/diego/.local/lib/python3.6/site-packages/binary_utils/binary_converter.py", line 101, in read_unsigned_triad_be
    return struct.unpack(">I", b"\x00" + data)[0]
struct.error: unpack requires a buffer of 4 bytes

### System Information

This server is running Podrum version 0.0.6 Platinum on API 0.0.1. This version is licensed under the GPL v2.0 license.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by HunterAzar** [comment]
That's world generator error.

**Comment by HunterAzar** [comment]
@SpiceX for now you can go to file "/home/diego/DocumentosPodrum\podrum\world\provider\anvil\region.py"
And change line 35 to open(path, "w").close()
