### ISSUE TITLE
Can't execute on macOS Monterey: ModuleNotFoundError

### ISSUE THREAD

**Issue by Atten007** [Podrum/PodrumLegacy#161]
### Summary

ModuleNotFoundError

### Reproduction Steps

I tried to execute the python script with Python 3.10.1 in the terminal on my Mac using macOS Monterey 12.2 beta 1. But then there came a very ****** error message named "ModuleNotFoundError" and this told me, that there's no module named 'nbt_utils'. https://pypi.org/project/nbt-utils/#files

### Expected Results

I expected that the server software created a MCPE server for me and my friends where we can play on.

### Actual Results

cd '/Users/mika/Downloads/Podrum-main/' && '/usr/local/bin/python3'  '/Users/mika/Downloads/Podrum-main/run.py'  && echo Exit status: $? && exit 1
(base) mika@Mac-Mika ~ % cd '/Users/mika/Downloads/Podrum-main/' && '/usr/local/bin/python3'  '/Users/mika/Downloads/Podrum-main/run.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/mika/Downloads/Podrum-main/run.py", line 15, in <module>
    from podrum.server import server
  File "/Users/mika/Downloads/Podrum-main/podrum/server.py", line 25, in <module>
    from podrum.managers import managers
  File "/Users/mika/Downloads/Podrum-main/podrum/managers.py", line 16, in <module>
    from podrum.block.block_manager import block_manager
  File "/Users/mika/Downloads/Podrum-main/podrum/block/block_manager.py", line 15, in <module>
    from podrum.item.item import item
  File "/Users/mika/Downloads/Podrum-main/podrum/item/item.py", line 16, in <module>
    from podrum.item.item_extra import item_extra
  File "/Users/mika/Downloads/Podrum-main/podrum/item/item_extra.py", line 16, in <module>
    from nbt_utils.tag.compound_tag import compound_tag
ModuleNotFoundError: No module named 'nbt_utils'

### System Information

macOS Monterey 12.2, iPadOS 15.3 iOS 15.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by HunterAzar** [comment]
do you have requirements installed?
```py
pip3 install -r requirements.txt
```

**Comment by Atten007** [comment]
> do you have requirements installed?
> 
> ```python
> pip3 install -r requirements.txt
> ```

Yes, I've installed it, but this very ****** issue still occurs and I can't fix it because I'm not a contributor. Can you pls fix it?

Sincerely yours,
Atten007😊

**Comment by HunterAzar** [comment]
> > do you have requirements installed?
> > 
> > ```python
> > pip3 install -r requirements.txt
> > ```
> 
> Yes, I've installed it, but this very ****** issue still occurs and I can't fix it because I'm not a contributor. Can you pls fix it?
> 
> Sincerely yours,
> Atten007😊

You can always make PR
Or join our discord and write to @MFDGaming

**Comment by Atten007** [comment]
What's PR? I'm asking you this because idk what PR should mean.

**Comment by Atten007** [comment]
I can't join my server... because the file "r.0.0.mca.lock" couldn't be found. Here's the log from this very ****** issue that lets me not join my Podrum server:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/mika/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/Users/mika/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/mika/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self.run()
  File "/Users/mika/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mika/Downloads/Podrum-main/podrum/world/world.py", line 90, in load_worker
    self.load_chunk(item[0], item[1])
  File "/Users/mika/Downloads/Podrum-main/podrum/world/world.py", line 52, in load_chunk
    chunk = self.provider.get_chunk(x, z)
    self._target(*self._args, **self._kwargs)
  File "/Users/mika/Downloads/Podrum-main/podrum/world/world.py", line 90, in load_worker
  File "/Users/mika/Downloads/Podrum-main/podrum/world/provider/anvil/anvil.py", line 104, in get_chunk
    self.load_chunk(item[0], item[1])
  File "/Users/mika/Downloads/Podrum-main/podrum/world/world.py", line 52, in load_chunk
    reg = region(region_path)
  File "/Users/mika/Downloads/Podrum-main/podrum/world/provider/anvil/region.py", line 43, in __init__
    chunk = self.provider.get_chunk(x, z)
  File "/Users/mika/Downloads/Podrum-main/podrum/world/provider/anvil/anvil.py", line 104, in get_chunk
    os.remove(path + ".lock")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mika/Downloads/Podrum-main/worlds/world/region/r.0.0.mca.lock'
    reg = region(region_path)
  File "/Users/mika/Downloads/Podrum-main/podrum/world/provider/anvil/region.py", line 43, in __init__
    os.remove(path + ".lock")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mika/Downloads/Podrum-main/worlds/world/region/r.0.0.mca.lock'

What I've made wrong here?

Sincerely yours,
Atten007😊

**Comment by Atten007** [comment]
Now everything worked fine =) I joined my server and now I'm playing on it!
