### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by plun1331** [Podrum/PodrumLegacy#61]
```
Traceback (most recent call last):
  File "c:/Users/-/Documents/GitHub/Podrum/src/__main__.py", line 32, in <module>
    Server(True)
  File "c:\Users\-\Documents\GitHub\Podrum\src\podrum\Server.py", line 70, in __init__
    Plugin.loadAll()
  File "c:\Users\-\Documents\GitHub\Podrum\src\podrum\plugin\Plugin.py", line 44, in loadAll
    if not self.pluginsDir.endswith("/") or not Plugin.pluginsDir.endswith("\\"):
NameError: name 'self' is not defined
```

**Comment by plun1331** [comment]
https://github.com/Podrum/Podrum/pull/62
