### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by dm-vev** [Podrum/PodrumLegacy#91]
When i connect to server, my minecraft client crashing and server gives me error:
Exception in thread Thread-62:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/podrum/podrum/world/world.py", line 51, in load_chunk_worker
    self.load_chunk(pos_and_player[0].x, pos_and_player[0].z)
  File "/root/podrum/podrum/world/world.py", line 32, in load_chunk
    chunk: object = self.provider.get_chunk(x, z)
  File "/root/podrum/podrum/world/provider/anvil/anvil.py", line 106, in get_chunk
    result.nbt_deserialize(chunk_data)
  File "/root/podrum/podrum/world/provider/anvil/chunk.py", line 145, in nbt_deserialize
    self.sections[section_tag.get_tag("Y").value] = section(
AttributeError: 'NoneType' object has no attribute 'value'

Minecraft version: 1.17.0.1
Podrum version: 0.0.6 Platinum

Sorry for my english!

**Comment by dm-vev** [comment]
and i tried connect from minecraft versions: 1.16.220, 1.16.210

**Comment by MFDGaming** [comment]
@dm-vev you must have 1.17.0

**Comment by MFDGaming** [comment]
just delete your podrum and use the latest version

**Comment by MFDGaming** [comment]
to start the lastest version do `python __main__.py` in windows and  `python3 __main__.py` in linux
